# Generated by Django 5.2.8 on 2025-11-25 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0002_orderpayment'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderservice',
            name='discount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=2, null=True, verbose_name='Discount'),
        ),
    ]
