# Generated by Django 5.2.8 on 2025-11-25 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0003_orderservice_discount'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderpart',
            name='discount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Discount'),
        ),
    ]
