# Generated by Django 5.2.8 on 2025-11-25 10:56

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0004_orderpart_discount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderpart',
            name='discount',
            field=models.DecimalField(blank=True, decimal_places=2, default=Decimal('0'), max_digits=5, null=True, verbose_name='Discount'),
        ),
        migrations.AlterField(
            model_name='orderservice',
            name='discount',
            field=models.DecimalField(blank=True, decimal_places=2, default=Decimal('0'), max_digits=5, null=True, verbose_name='Discount'),
        ),
    ]
